# Use an official Node.js LTS (Long-Term Support) image as the base
FROM node:lts-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and yarn.lock files to the container
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Set the development environment variable
ENV NODE_ENV=development

# Expose the desired port (adjust as needed)
EXPOSE 5173

# Specify the command to start the React development server with live reloading
CMD ["npm", "run", "dev"]
